export const seedData = {
  Users: [
    {
      user_id: 1,
      name: 'Liam Brown',
      email: 'liam.brown@example.com',
      password_hash: 'hashed_pw_1',
      role: 'lawyer',
      created_at: '2025-11-01T10:00:00Z',
    },
    {
      user_id: 2,
      name: 'Olivia Green',
      email: 'olivia.green@example.com',
      password_hash: 'hashed_pw_2',
      role: 'accountant',
      created_at: '2025-11-02T11:00:00Z',
    },
    {
      user_id: 3,
      name: 'Noah Wilson',
      email: 'noah.wilson@example.com',
      password_hash: 'hashed_pw_3',
      role: 'client',
      created_at: '2025-11-03T12:00:00Z',
    },
    {
      user_id: 4,
      name: 'Emma Taylor',
      email: 'emma.taylor@example.com',
      password_hash: 'hashed_pw_4',
      role: 'lawyer',
      created_at: '2025-11-04T13:00:00Z',
    },
    {
      user_id: 5,
      name: 'Oliver Jones',
      email: 'oliver.jones@example.com',
      password_hash: 'hashed_pw_5',
      role: 'accountant',
      created_at: '2025-11-05T14:00:00Z',
    },
    {
      user_id: 6,
      name: 'Ava Williams',
      email: 'ava.williams@example.com',
      password_hash: 'hashed_pw_6',
      role: 'client',
      created_at: '2025-11-06T15:00:00Z',
    },
    {
      user_id: 7,
      name: 'James Johnson',
      email: 'james.johnson@example.com',
      password_hash: 'hashed_pw_7',
      role: 'lawyer',
      created_at: '2025-11-07T16:00:00Z',
    },
    {
      user_id: 8,
      name: 'Sophia Miller',
      email: 'sophia.miller@example.com',
      password_hash: 'hashed_pw_8',
      role: 'accountant',
      created_at: '2025-11-08T17:00:00Z',
    },
    {
      user_id: 9,
      name: 'Benjamin Davis',
      email: 'benjamin.davis@example.com',
      password_hash: 'hashed_pw_9',
      role: 'client',
      created_at: '2025-11-09T18:00:00Z',
    },
    {
      user_id: 10,
      name: 'Isabella Garcia',
      email: 'isabella.garcia@example.com',
      password_hash: 'hashed_pw_10',
      role: 'lawyer',
      created_at: '2025-11-10T19:00:00Z',
    },
    {
      user_id: 11,
      name: 'Lucas Rodriguez',
      email: 'lucas.rodriguez@example.com',
      password_hash: 'hashed_pw_11',
      role: 'accountant',
      created_at: '2025-11-11T20:00:00Z',
    },
    {
      user_id: 12,
      name: 'Mia Martinez',
      email: 'mia.martinez@example.com',
      password_hash: 'hashed_pw_12',
      role: 'client',
      created_at: '2025-11-12T21:00:00Z',
    },
    {
      user_id: 13,
      name: 'Henry Hernandez',
      email: 'henry.hernandez@example.com',
      password_hash: 'hashed_pw_13',
      role: 'lawyer',
      created_at: '2025-11-13T22:00:00Z',
    },
    {
      user_id: 14,
      name: 'Amelia Lopez',
      email: 'amelia.lopez@example.com',
      password_hash: 'hashed_pw_14',
      role: 'accountant',
      created_at: '2025-11-14T23:00:00Z',
    },
    {
      user_id: 15,
      name: 'Alexander Gonzalez',
      email: 'alexander.gonzalez@example.com',
      password_hash: 'hashed_pw_15',
      role: 'client',
      created_at: '2025-11-15T10:00:00Z',
    },
    // ... continue for 35 more users
    {
      user_id: 16,
      name: 'Charlotte Perez',
      email: 'charlotte.perez@example.com',
      password_hash: 'hashed_pw_16',
      role: 'lawyer',
      created_at: '2025-11-16T11:00:00Z',
    },
    {
      user_id: 17,
      name: 'Daniel Sanchez',
      email: 'daniel.sanchez@example.com',
      password_hash: 'hashed_pw_17',
      role: 'accountant',
      created_at: '2025-11-17T12:00:00Z',
    },
    {
      user_id: 18,
      name: 'Harper Rivera',
      email: 'harper.rivera@example.com',
      password_hash: 'hashed_pw_18',
      role: 'client',
      created_at: '2025-11-18T13:00:00Z',
    },
    {
      user_id: 19,
      name: 'Matthew King',
      email: 'matthew.king@example.com',
      password_hash: 'hashed_pw_19',
      role: 'lawyer',
      created_at: '2025-11-19T14:00:00Z',
    },
    {
      user_id: 20,
      name: 'Evelyn Wright',
      email: 'evelyn.wright@example.com',
      password_hash: 'hashed_pw_20',
      role: 'accountant',
      created_at: '2025-11-20T15:00:00Z',
    },
    {
      user_id: 21,
      name: 'Aiden Scott',
      email: 'aiden.scott@example.com',
      password_hash: 'hashed_pw_21',
      role: 'client',
      created_at: '2025-11-21T16:00:00Z',
    },
    {
      user_id: 22,
      name: 'Abigail Green',
      email: 'abigail.green@example.com',
      password_hash: 'hashed_pw_22',
      role: 'lawyer',
      created_at: '2025-11-22T17:00:00Z',
    },
    {
      user_id: 23,
      name: 'Joseph Adams',
      email: 'joseph.adams@example.com',
      password_hash: 'hashed_pw_23',
      role: 'accountant',
      created_at: '2025-11-23T18:00:00Z',
    },
    {
      user_id: 24,
      name: 'Ella Baker',
      email: 'ella.baker@example.com',
      password_hash: 'hashed_pw_24',
      role: 'client',
      created_at: '2025-11-24T19:00:00Z',
    },
    {
      user_id: 25,
      name: 'David Nelson',
      email: 'david.nelson@example.com',
      password_hash: 'hashed_pw_25',
      role: 'lawyer',
      created_at: '2025-11-25T20:00:00Z',
    },
    {
      user_id: 26,
      name: 'Grace Carter',
      email: 'grace.carter@example.com',
      password_hash: 'hashed_pw_26',
      role: 'accountant',
      created_at: '2025-11-26T21:00:00Z',
    },
    {
      user_id: 27,
      name: 'Samuel Mitchell',
      email: 'samuel.mitchell@example.com',
      password_hash: 'hashed_pw_27',
      role: 'client',
      created_at: '2025-11-27T22:00:00Z',
    },
    {
      user_id: 28,
      name: 'Victoria Perez',
      email: 'victoria.perez@example.com',
      password_hash: 'hashed_pw_28',
      role: 'lawyer',
      created_at: '2025-11-28T23:00:00Z',
    },
    {
      user_id: 29,
      name: 'Christopher Roberts',
      email: 'christopher.roberts@example.com',
      password_hash: 'hashed_pw_29',
      role: 'accountant',
      created_at: '2025-11-29T10:00:00Z',
    },
    {
      user_id: 30,
      name: 'Chloe Turner',
      email: 'chloe.turner@example.com',
      password_hash: 'hashed_pw_30',
      role: 'client',
      created_at: '2025-11-30T11:00:00Z',
    },
    {
      user_id: 31,
      name: 'Andrew Phillips',
      email: 'andrew.phillips@example.com',
      password_hash: 'hashed_pw_31',
      role: 'lawyer',
      created_at: '2025-12-01T12:00:00Z',
    },
    {
      user_id: 32,
      name: 'Madison Campbell',
      email: 'madison.campbell@example.com',
      password_hash: 'hashed_pw_32',
      role: 'accountant',
      created_at: '2025-12-02T13:00:00Z',
    },
    {
      user_id: 33,
      name: 'Joshua Parker',
      email: 'joshua.parker@example.com',
      password_hash: 'hashed_pw_33',
      role: 'client',
      created_at: '2025-12-03T14:00:00Z',
    },
    {
      user_id: 34,
      name: 'Lauren Evans',
      email: 'lauren.evans@example.com',
      password_hash: 'hashed_pw_34',
      role: 'lawyer',
      created_at: '2025-12-04T15:00:00Z',
    },
    {
      user_id: 35,
      name: 'Ryan Edwards',
      email: 'ryan.edwards@example.com',
      password_hash: 'hashed_pw_35',
      role: 'accountant',
      created_at: '2025-12-05T16:00:00Z',
    },
    {
      user_id: 36,
      name: 'Megan Collins',
      email: 'megan.collins@example.com',
      password_hash: 'hashed_pw_36',
      role: 'client',
      created_at: '2025-12-06T17:00:00Z',
    },
    {
      user_id: 37,
      name: 'Brandon Stewart',
      email: 'brandon.stewart@example.com',
      password_hash: 'hashed_pw_37',
      role: 'lawyer',
      created_at: '2025-12-07T18:00:00Z',
    },
    {
      user_id: 38,
      name: 'Kayla Sanchez',
      email: 'kayla.sanchez@example.com',
      password_hash: 'hashed_pw_38',
      role: 'accountant',
      created_at: '2025-12-08T19:00:00Z',
    },
    {
      user_id: 39,
      name: 'Justin Morris',
      email: 'justin.morris@example.com',
      password_hash: 'hashed_pw_39',
      role: 'client',
      created_at: '2025-12-09T20:00:00Z',
    },
    {
      user_id: 40,
      name: 'Hannah Rogers',
      email: 'hannah.rogers@example.com',
      password_hash: 'hashed_pw_40',
      role: 'lawyer',
      created_at: '2025-12-10T21:00:00Z',
    },
    {
      user_id: 41,
      name: 'Kevin Reed',
      email: 'kevin.reed@example.com',
      password_hash: 'hashed_pw_41',
      role: 'accountant',
      created_at: '2025-12-11T22:00:00Z',
    },
    {
      user_id: 42,
      name: 'Ashley Cook',
      email: 'ashley.cook@example.com',
      password_hash: 'hashed_pw_42',
      role: 'client',
      created_at: '2025-12-12T23:00:00Z',
    },
    {
      user_id: 43,
      name: 'Jason Morgan',
      email: 'jason.morgan@example.com',
      password_hash: 'hashed_pw_43',
      role: 'lawyer',
      created_at: '2025-12-13T10:00:00Z',
    },
    {
      user_id: 44,
      name: 'Brianna Bailey',
      email: 'brianna.bailey@example.com',
      password_hash: 'hashed_pw_44',
      role: 'accountant',
      created_at: '2025-12-14T11:00:00Z',
    },
    {
      user_id: 45,
      name: 'Robert Bell',
      email: 'robert.bell@example.com',
      password_hash: 'hashed_pw_45',
      role: 'client',
      created_at: '2025-12-15T12:00:00Z',
    },
    {
      user_id: 46,
      name: 'Samantha Cooper',
      email: 'samantha.cooper@example.com',
      password_hash: 'hashed_pw_46',
      role: 'lawyer',
      created_at: '2025-12-16T13:00:00Z',
    },
    {
      user_id: 47,
      name: 'Tyler Richardson',
      email: 'tyler.richardson@example.com',
      password_hash: 'hashed_pw_47',
      role: 'accountant',
      created_at: '2025-12-17T14:00:00Z',
    },
    {
      user_id: 48,
      name: 'Taylor Cox',
      email: 'taylor.cox@example.com',
      password_hash: 'hashed_pw_48',
      role: 'client',
      created_at: '2025-12-18T15:00:00Z',
    },
    {
      user_id: 49,
      name: 'Stephanie Howard',
      email: 'stephanie.howard@example.com',
      password_hash: 'hashed_pw_49',
      role: 'lawyer',
      created_at: '2025-12-19T16:00:00Z',
    },
    {
      user_id: 50,
      name: 'Zachary Ward',
      email: 'zachary.ward@example.com',
      password_hash: 'hashed_pw_50',
      role: 'accountant',
      created_at: '2025-12-20T17:00:00Z',
    },
    {
      user_id: 51,
      name: 'Ethan Hunt',
      email: 'ethan.hunt@example.com',
      password_hash: 'hashed_pw_51',
      role: 'lawyer',
      created_at: '2025-12-21T10:00:00Z',
    },
    {
      user_id: 52,
      name: 'Chloe King',
      email: 'chloe.king@example.com',
      password_hash: 'hashed_pw_52',
      role: 'accountant',
      created_at: '2025-12-21T11:00:00Z',
    },
    {
      user_id: 53,
      name: 'Logan Hill',
      email: 'logan.hill@example.com',
      password_hash: 'hashed_pw_53',
      role: 'lawyer',
      created_at: '2025-12-22T10:00:00Z',
    },
    {
      user_id: 54,
      name: 'Zoe Scott',
      email: 'zoe.scott@example.com',
      password_hash: 'hashed_pw_54',
      role: 'accountant',
      created_at: '2025-12-22T11:00:00Z',
    },
    {
      user_id: 55,
      name: 'Aaron Green',
      email: 'aaron.green@example.com',
      password_hash: 'hashed_pw_55',
      role: 'lawyer',
      created_at: '2025-12-23T10:00:00Z',
    },
    {
      user_id: 56,
      name: 'Lily Adams',
      email: 'lily.adams@example.com',
      password_hash: 'hashed_pw_56',
      role: 'accountant',
      created_at: '2025-12-23T11:00:00Z',
    },
    {
      user_id: 57,
      name: 'Owen Nelson',
      email: 'owen.nelson@example.com',
      password_hash: 'hashed_pw_57',
      role: 'lawyer',
      created_at: '2025-12-24T10:00:00Z',
    },
    {
      user_id: 58,
      name: 'Nora Baker',
      email: 'nora.baker@example.com',
      password_hash: 'hashed_pw_58',
      role: 'accountant',
      created_at: '2025-12-24T11:00:00Z',
    },
    {
      user_id: 59,
      name: 'Caleb Carter',
      email: 'caleb.carter@example.com',
      password_hash: 'hashed_pw_59',
      role: 'lawyer',
      created_at: '2025-12-25T10:00:00Z',
    },
    {
      user_id: 60,
      name: 'Hannah Wright',
      email: 'hannah.wright@example.com',
      password_hash: 'hashed_pw_60',
      role: 'accountant',
      created_at: '2025-12-25T11:00:00Z',
    },
  ],

  Profiles: [
    {
      profile_id: 1,
      user_id: 1,
      specialization: 'Corporate Law',
      experience_years: 10,
      bio: 'A highly experienced corporate lawyer with a decade of practice, focusing on mergers, acquisitions, and corporate governance. My goal is to provide strategic, clear, and effective legal solutions that drive business growth and mitigate risk.',
      rating_avg: 4.8,
      profile_photo_url: 'https://example.com/photos/liam.jpg',
      location: 'London, UK',
    },
    {
      profile_id: 2,
      user_id: 2,
      specialization: 'Forensic Accounting',
      experience_years: 7,
      bio: 'As a certified forensic accountant, I specialize in investigating financial discrepancies and fraud. I am dedicated to uncovering the truth with meticulous attention to detail and a commitment to ethical standards.',
      rating_avg: 4.6,
      profile_photo_url: 'https://example.com/photos/olivia.jpg',
      location: 'Manchester, UK',
    },
    {
      profile_id: 3,
      user_id: 4,
      specialization: 'Intellectual Property Law',
      experience_years: 5,
      bio: 'I help creators and innovators protect their valuable intellectual assets, including patents, trademarks, and copyrights. My passion is to ensure that your hard work and creativity are legally safeguarded.',
      rating_avg: 4.9,
      profile_photo_url: 'https://example.com/photos/emma.jpg',
      location: 'Birmingham, UK',
    },
    {
      profile_id: 4,
      user_id: 5,
      specialization: 'Tax Accounting',
      experience_years: 12,
      bio: 'With over a decade in tax accounting, I provide comprehensive tax planning and compliance services for individuals and businesses. My approach is proactive, aiming to optimize your financial position while ensuring full compliance.',
      rating_avg: 4.7,
      profile_photo_url: 'https://example.com/photos/oliver.jpg',
      location: 'Glasgow, UK',
    },
    {
      profile_id: 5,
      user_id: 51,
      specialization: 'Family Law',
      experience_years: 8,
      bio: 'Compassionate and dedicated family lawyer with extensive experience in divorce, child custody, and adoption cases. My focus is on finding amicable and fair resolutions for families during challenging times.',
      rating_avg: 4.7,
      profile_photo_url: 'https://example.com/photos/ethan.jpg',
      location: 'Edinburgh, UK',
    },
    {
      profile_id: 6,
      user_id: 52,
      specialization: 'Management Accounting',
      experience_years: 6,
      bio: 'A strategic management accountant focused on improving business performance through detailed financial analysis, budgeting, and forecasting. I help companies make informed decisions to drive profitability and growth.',
      rating_avg: 4.8,
      profile_photo_url: 'https://example.com/photos/chloe.jpg',
      location: 'Cardiff, UK',
    },
    {
      profile_id: 7,
      user_id: 53,
      specialization: 'Criminal Defense Law',
      experience_years: 12,
      bio: 'A seasoned criminal defense attorney with a strong track record of successfully defending clients. I am committed to protecting the rights of the accused and ensuring a fair legal process for everyone.',
      rating_avg: 4.9,
      profile_photo_url: 'https://example.com/photos/logan.jpg',
      location: 'Liverpool, UK',
    },
    {
      profile_id: 8,
      user_id: 54,
      specialization: 'Audit and Assurance',
      experience_years: 9,
      bio: 'Detail-oriented auditor providing thorough and independent financial statement audits. My work ensures regulatory compliance and provides stakeholders with confidence in the financial reporting.',
      rating_avg: 4.6,
      profile_photo_url: 'https://example.com/photos/zoe.jpg',
      location: 'Bristol, UK',
    },
    {
      profile_id: 9,
      user_id: 55,
      specialization: 'Real Estate Law',
      experience_years: 7,
      bio: 'Expert in all aspects of real estate law, including residential and commercial transactions, leasing, and property disputes. I strive to make every property transaction smooth and secure for my clients.',
      rating_avg: 4.8,
      profile_photo_url: 'https://example.com/photos/aaron.jpg',
      location: 'Leeds, UK',
    },
    {
      profile_id: 10,
      user_id: 56,
      specialization: 'Non-Profit Accounting',
      experience_years: 10,
      bio: 'Passionate about helping non-profit organizations achieve their missions through sound financial management. I specialize in grant management, compliance, and reporting for the charitable sector.',
      rating_avg: 4.9,
      profile_photo_url: 'https://example.com/photos/lily.jpg',
      location: 'Sheffield, UK',
    },
    {
      profile_id: 11,
      user_id: 57,
      specialization: 'Employment Law',
      experience_years: 6,
      bio: 'Dedicated to advising both employers and employees on their rights and obligations in the workplace. I handle cases involving contracts, discrimination, and unfair dismissal with professionalism and care.',
      rating_avg: 4.7,
      profile_photo_url: 'https://example.com/photos/owen.jpg',
      location: 'Newcastle, UK',
    },
    {
      profile_id: 12,
      user_id: 58,
      specialization: 'Personal Tax Services',
      experience_years: 15,
      bio: 'With 15 years of experience, I offer personalized tax advice and preparation services for individuals, including freelancers and high-net-worth clients. My goal is to maximize your returns and minimize your stress.',
      rating_avg: 4.8,
      profile_photo_url: 'https://example.com/photos/nora.jpg',
      location: 'Nottingham, UK',
    },
  ],

  Services: [
    {
      service_id: 1,
      profile_id: 1,
      title: 'Mergers & Acquisitions Legal Advisory',
      description:
        'Comprehensive legal support for all stages of mergers and acquisitions, from due diligence to post-merger integration. Ensuring a smooth and legally sound transaction.',
      price_range: '£5000–£20000',
      availability: 'By appointment',
      created_at: '2025-11-05T09:00:00Z',
    },
    {
      service_id: 2,
      profile_id: 2,
      title: 'Financial Fraud Investigation',
      description:
        'In-depth investigation of suspected financial fraud, including asset tracing, data analysis, and litigation support. I provide clear reports to support legal action.',
      price_range: '£800–£3000',
      availability: 'Weekdays 9–5',
      created_at: '2025-11-06T09:00:00Z',
    },
    {
      service_id: 3,
      profile_id: 3,
      title: 'Trademark Registration',
      description:
        'Complete service for trademark searching, application, and registration to protect your brand identity. I handle the entire process with the IPO.',
      price_range: '£400–£1200',
      availability: 'Mon-Fri, 10am-4pm',
      created_at: '2025-11-07T09:00:00Z',
    },
    {
      service_id: 4,
      profile_id: 4,
      title: 'Corporate Tax Planning',
      description:
        'Strategic tax planning services for corporations to minimize tax liabilities and maximize savings. This includes advice on structuring and investments.',
      price_range: '£500–£2500',
      availability: 'Weekdays',
      created_at: '2025-11-08T09:00:00Z',
    },
    {
      service_id: 5,
      profile_id: 5,
      title: 'Divorce Petition Filing',
      description:
        'Comprehensive assistance with filing for divorce, including all necessary paperwork and legal guidance to ensure the process is handled correctly and efficiently from the start.',
      price_range: '£600–£1500',
      availability: 'By appointment',
      created_at: '2025-12-22T09:00:00Z',
    },
    {
      service_id: 6,
      profile_id: 6,
      title: 'Business Budgeting and Forecasting',
      description:
        'Developing detailed budgets and financial forecasts to help your business plan for the future, manage cash flow, and make strategic decisions with confidence.',
      price_range: '£700–£2000',
      availability: 'Weekdays',
      created_at: '2025-12-22T10:00:00Z',
    },
    {
      service_id: 7,
      profile_id: 7,
      title: 'Criminal Defense Consultation',
      description:
        'Initial consultation to discuss the details of a criminal charge, review evidence, and provide a clear overview of legal options and potential defense strategies.',
      price_range: '£150–£300',
      availability: '24/7 for emergencies',
      created_at: '2025-12-23T09:00:00Z',
    },
    {
      service_id: 8,
      profile_id: 8,
      title: 'Internal Audit Service',
      description:
        'A complete internal audit to assess your company’s financial health, risk management processes, and internal controls, providing assurance to leadership and stakeholders.',
      price_range: '£2000–£10000',
      availability: 'By project',
      created_at: '2025-12-23T10:00:00Z',
    },
    {
      service_id: 9,
      profile_id: 1,
      title: 'Corporate Governance Review',
      description:
        'Reviewing and advising on corporate governance structures to ensure compliance with UK law and best practices, protecting directors and shareholders.',
      price_range: '£1500–£4000',
      availability: 'By appointment',
      created_at: '2025-12-24T09:00:00Z',
    },
    {
      service_id: 10,
      profile_id: 9,
      title: 'Commercial Lease Review',
      description:
        'Expert legal review of commercial lease agreements to identify potential risks and ensure favorable terms for your business before you sign.',
      price_range: '£500–£1200',
      availability: 'Weekdays 9–5',
      created_at: '2025-12-26T09:00:00Z',
    },
    {
      service_id: 11,
      profile_id: 10,
      title: 'Non-Profit Grant Compliance',
      description:
        'Specialized accounting services to ensure your non-profit organization meets all financial reporting and compliance requirements for grant funding.',
      price_range: '£400–£1500',
      availability: 'By appointment',
      created_at: '2025-12-26T10:00:00Z',
    },
    {
      service_id: 12,
      profile_id: 11,
      title: 'Employee Contract Drafting',
      description:
        'Drafting clear and legally compliant employment contracts to protect your business and establish fair terms for your employees.',
      price_range: '£300–£800',
      availability: 'Mon-Fri, 10am-4pm',
      created_at: '2025-12-27T09:00:00Z',
    },
    {
      service_id: 13,
      profile_id: 12,
      title: 'Freelancer Tax Return Service',
      description:
        'Comprehensive tax return preparation and filing service specifically for freelancers and self-employed individuals, ensuring you claim all eligible expenses.',
      price_range: '£200–£500',
      availability: 'Weekdays',
      created_at: '2025-12-27T10:00:00Z',
    },
  ],

  Bookings: [
    {
      booking_id: 1,
      service_id: 1,
      client_id: 3,
      status: 'confirmed',
      message:
        'We are considering a potential acquisition and require an experienced lawyer to guide us through the initial due diligence phase. The target is a small tech company.',
      created_at: '2025-11-10T14:00:00Z',
    },
    {
      booking_id: 2,
      service_id: 2,
      client_id: 6,
      status: 'pending',
      message:
        'I suspect an employee has been manipulating expense reports. I need a forensic accountant to discreetly investigate and provide evidence.',
      created_at: '2025-11-11T15:00:00Z',
    },
    {
      booking_id: 3,
      service_id: 3,
      client_id: 9,
      status: 'completed',
      message:
        'I have a new brand logo and name for my startup and I want to ensure it is properly trademarked in the UK. Please advise on the process and costs.',
      created_at: '2025-11-12T16:00:00Z',
    },
    {
      booking_id: 4,
      service_id: 4,
      client_id: 12,
      status: 'confirmed',
      message:
        'Our company is looking for a new accountant to handle our corporate tax strategy for the upcoming fiscal year. We want to explore all legal avenues for tax reduction.',
      created_at: '2025-11-13T17:00:00Z',
    },
    {
      booking_id: 5,
      service_id: 5,
      client_id: 21,
      status: 'completed',
      message:
        'I need assistance with the legal process of filing for divorce. It is an amicable separation, and we want to ensure all paperwork is handled correctly.',
      created_at: '2025-12-23T11:00:00Z',
    },
    {
      booking_id: 6,
      service_id: 6,
      client_id: 24,
      status: 'completed',
      message:
        'My small business is growing, and I need help creating a proper budget and financial forecast for the next two years. Looking for a strategic accountant.',
      created_at: '2025-12-24T12:00:00Z',
    },
    {
      booking_id: 7,
      service_id: 7,
      client_id: 39,
      status: 'completed',
      message:
        'I need an urgent consultation regarding a minor legal issue. Please let me know your availability for a brief call.',
      created_at: '2025-12-28T14:00:00Z',
    },
    {
      booking_id: 8,
      service_id: 11,
      client_id: 30,
      status: 'completed',
      message:
        'Our non-profit has received a new government grant, and we need an accountant to help us set up our financial tracking for compliance.',
      created_at: '2025-12-28T15:00:00Z',
    },
    {
      booking_id: 9,
      service_id: 12,
      client_id: 33,
      status: 'completed',
      message:
        'We are hiring our first full-time employee and need a standard employment contract drafted that is compliant with UK employment law.',
      created_at: '2025-12-29T10:00:00Z',
    },
    {
      booking_id: 10,
      service_id: 13,
      client_id: 42,
      status: 'completed',
      message:
        "I'm a freelance designer and need help with my self-assessment tax return for this year. I want to make sure I'm claiming all my expenses correctly.",
      created_at: '2025-12-30T11:00:00Z',
    },
    {
      booking_id: 11,
      service_id: 8,
      client_id: 45,
      status: 'completed',
      message:
        'We require a full internal audit for our mid-sized company before the end of the fiscal year. Please provide a quote and timeline.',
      created_at: '2026-01-02T09:00:00Z',
    },
    {
      booking_id: 12,
      service_id: 10,
      client_id: 27,
      status: 'completed',
      message:
        'I am about to sign a lease for a new retail space and need a lawyer to review the commercial lease agreement to ensure my interests are protected.',
      created_at: '2025-12-28T14:00:00Z',
    },
  ],

  Reviews: [
    {
      review_id: 1,
      service_id: 3,
      client_id: 9,
      rating: 5,
      comment:
        'Emma was absolutely fantastic. She made the complex process of trademarking my brand feel simple and straightforward. Her communication was excellent, and she was always available to answer my questions. I felt completely supported and confident in her abilities. Highly recommended!',
      created_at: '2025-11-20T16:00:00Z',
    },
    {
      review_id: 2,
      service_id: 1,
      client_id: 3,
      rating: 4,
      comment:
        'Liam provided very solid legal advice for our M&A activities. His expertise was evident, and he helped us navigate some tricky negotiation points. The only reason for not giving five stars is that the final report was a day later than promised, but the quality of the work was undeniable.',
      created_at: '2025-11-22T17:00:00Z',
    },
    {
      review_id: 3,
      service_id: 2,
      client_id: 6,
      rating: 5,
      comment:
        'Olivia was incredibly professional and discreet. She uncovered the financial discrepancies we suspected with remarkable speed and provided a clear, detailed report that was instrumental for our internal proceedings. Her expertise in forensic accounting is top-notch.',
      created_at: '2025-11-25T10:00:00Z',
    },
    {
      review_id: 4,
      service_id: 4,
      client_id: 12,
      rating: 5,
      comment:
        'Oliver has transformed our approach to corporate tax. His strategic advice was not only compliant but also innovative, leading to significant savings for our company. He is proactive, knowledgeable, and an absolute pleasure to work with. Highly recommend his services.',
      created_at: '2025-11-28T11:00:00Z',
    },
    {
      review_id: 5,
      service_id: 1,
      client_id: 15,
      rating: 4,
      comment:
        'We engaged Liam for legal advisory on a potential merger. His knowledge of corporate law is extensive, and his guidance was crucial. The process took a bit longer than we anticipated, but the outcome was successful, and his contribution was invaluable.',
      created_at: '2025-12-01T14:00:00Z',
    },
    {
      review_id: 6,
      service_id: 3,
      client_id: 18,
      rating: 5,
      comment:
        'Emma made the trademark registration process for our new product line completely seamless. She was organized, efficient, and her communication was outstanding. We felt confident and well-informed every step of the way. An excellent experience all around.',
      created_at: '2025-12-05T18:00:00Z',
    },
    {
      review_id: 7,
      service_id: 5,
      client_id: 21,
      rating: 5,
      comment:
        'Ethan handled my divorce filing with great sensitivity and professionalism. He made a difficult process feel manageable and clear. His guidance was invaluable, and I am grateful for his support. I would recommend him to anyone in a similar situation.',
      created_at: '2025-12-28T10:00:00Z',
    },
    {
      review_id: 8,
      service_id: 9,
      client_id: 3,
      rating: 5,
      comment:
        'This is the second time we have worked with Liam, this time for a corporate governance review. Once again, his advice was sharp, practical, and perfectly aligned with our business needs. His expertise is truly an asset to any company.',
      created_at: '2025-12-29T16:00:00Z',
    },
    {
      review_id: 9,
      service_id: 10,
      client_id: 27,
      rating: 5,
      comment:
        'Aaron was fantastic. He reviewed our commercial lease very thoroughly and identified several key areas for negotiation that saved us a lot of potential trouble down the line. His advice was clear, and the turnaround was fast. Highly recommended for any real estate legal matters.',
      created_at: '2026-01-05T12:00:00Z',
    },
    {
      review_id: 10,
      service_id: 12,
      client_id: 33,
      rating: 5,
      comment:
        "Owen drafted an employment contract for us that was exactly what we needed. He was very knowledgeable about employment law and took the time to explain the clauses and their implications. The process was smooth and professional. We'll definitely be using his services again.",
      created_at: '2026-01-06T14:00:00Z',
    },
    {
      review_id: 11,
      service_id: 6,
      client_id: 24,
      rating: 2,
      comment:
        'The final budget and forecast were delivered, but the process was frustrating. Communication was poor, and I often had to chase for updates. The forecast also seemed overly optimistic and lacked the detailed assumptions I was expecting. Disappointing experience.',
      created_at: '2026-01-08T11:00:00Z',
    },
    {
      review_id: 12,
      service_id: 7,
      client_id: 39,
      rating: 1,
      comment:
        'The consultation felt rushed and dismissive. Logan seemed uninterested in the details of my case and provided very generic advice that I could have found online. A complete waste of money. I would not recommend him for any criminal defense matters.',
      created_at: '2026-01-09T15:00:00Z',
    },
    {
      review_id: 13,
      service_id: 11,
      client_id: 30,
      rating: 5,
      comment:
        'Lily was a lifesaver for our non-profit. She expertly navigated the complexities of grant compliance and set up a system that is easy for us to manage. Her knowledge and passion for the non-profit sector are truly impressive. Thank you, Lily!',
      created_at: '2026-01-10T10:00:00Z',
    },
    {
      review_id: 14,
      service_id: 13,
      client_id: 42,
      rating: 4,
      comment:
        "Nora did a great job on my tax return and found several deductions I wasn't aware of. The only small issue was a delay in getting the final documents, but the quality of the work was excellent and she saved me money. I would use her service again.",
      created_at: '2026-01-12T16:00:00Z',
    },
    {
      review_id: 15,
      service_id: 8,
      client_id: 45,
      rating: 3,
      comment:
        "The internal audit was completed, but it took much longer than quoted and caused some disruption to our team. While Zoe's final report was thorough, the project management and communication could have been significantly better. An average experience overall.",
      created_at: '2026-01-20T17:00:00Z',
    },
  ],
}
